//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VideoPlayerDenemeVideojs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kurs
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Kurs()
        {
            this.UyeKurs = new HashSet<UyeKurs>();
            this.Video = new HashSet<Video>();
        }
    
        public int Id { get; set; }
        public bool Silindi { get; set; }
        public string Ad { get; set; }
        public string Acikklama { get; set; }
        public string Icerik { get; set; }
        public Nullable<decimal> Fiyat { get; set; }
        public Nullable<System.DateTime> SonGuncellemeTarih { get; set; }
        public Nullable<int> KategoriID { get; set; }
        public Nullable<int> UstKategoriID { get; set; }
        public string Resim { get; set; }
        public Nullable<bool> Ücretsiz { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UyeKurs> UyeKurs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Video> Video { get; set; }
    }
}
