//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VideoPlayerDenemeVideojs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Video
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Video()
        {
            this.UyeVideo = new HashSet<UyeVideo>();
        }
    
        public int Id { get; set; }
        public Nullable<int> KursID { get; set; }
        public string VideoAdı { get; set; }
        public string Suresi { get; set; }
        public Nullable<int> BolumID { get; set; }
        public string Link { get; set; }
    
        public virtual Kurs Kurs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UyeVideo> UyeVideo { get; set; }
    }
}
